[build]
  command = "CI= npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/slack"
  to = "/.netlify/functions/slack"
  status = 200
  force = true
